task:
  skip: $CIRRUS_BRANCH == 'master'
  name: Run mutation
  container:
    image: ubuntu:jammy
    cpu: 8
    memory: 8G
  env:
    SERVER_URL: "ENCRYPTED[ada8a0402756f265573a40d0b6396b99fe1c92433e5ff679033fb3064cce41b9b5d5a3231a8ca267826522e7e852e11d]"
    SERVER_TOKEN: "ENCRYPTED[58406046ab489e798b2eff157f053c3a83bce7c37759c948095e93ca04542e35fe108dcbe0ad5b47d3400c7a5a37fea4]"

  install_script:
    - apt update
    - apt install -y build-essential libtool autotools-dev automake pkg-config bsdmainutils python3 libevent-dev libboost-dev libsqlite3-dev ccache git curl wget
  
  build_script:
    - curl "$SERVER_URL/mutations/$CIRRUS_CHANGE_TITLE" -X POST -H "Authorization:$SERVER_TOKEN" -H 'Content-Type:application/json' -d "{\"mutation_id\":\"$CIRRUS_CHANGE_TITLE\", \"status\":\"Running\"}"
    - ./autogen.sh
    - ./test/get_previous_releases.py -b -t ./releases
    - ./contrib/install_db4.sh `pwd`
    - export BDB_PREFIX="$PWD/db4"
    - ./configure BDB_LIBS="-L${BDB_PREFIX}/lib -ldb_cxx-4.8" BDB_CFLAGS="-I${BDB_PREFIX}/include" --enable-zmq --disable-bench --enable-extended-functional-tests
    - make -j8
    - make check -j9
    - python3 test/functional/test_runner.py -j12 -F
    - curl "$SERVER_URL/mutations/$CIRRUS_CHANGE_TITLE" -X POST -H "Authorization:$SERVER_TOKEN" -H 'Content-Type:application/json' -d "{\"mutation_id\":\"$CIRRUS_CHANGE_TITLE\", \"status\":\"NotKilled\"}"
